version: '3.8'

services:
  main-page:
    build: .
    image: main_page:latest
    container_name: main_page
    restart: unless-stopped
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - web

networks:
  web:
    external: true
    name: nginxproxymanager_default
