version: '3.8'

services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    restart: always
    ports:
      - "1194:1194/udp"
    volumes:
      - ./ovpn-data:/etc/openvpn
    environment:
      - DEBUG=1
