version: '3.8'

services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    restart: always
    ports:
      - "1194:1194/udp"
    volumes:
      - ./ovpn-data:/etc/openvpn
    environment:
      - DEBUG=1
    devices:
      - "/dev/net/tun:/dev/net/tun"
    sysctls:
      net.ipv4.ip_forward: "1"
      net.ipv6.conf.all.disable_ipv6: "1"
      net.ipv6.conf.default.forwarding: "1"
      net.ipv6.conf.all.forwarding: "1"
