version: "3"
services:
  owncast:
    image: owncast/owncast:latest
    ports:
      - "8181:8080"
      - "1935:1935"
    volumes:
      - ./data:/app/data
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.owncast.rule=Host(`stream.melikbugraozcelik.com`)"
      - "traefik.http.routers.owncast.entrypoints=websecure"
      - "traefik.http.routers.owncast.tls.certresolver=le"
      - "traefik.http.routers.owncast.middlewares=hsts@file"
      - "traefik.http.services.owncast.loadbalancer.server.port=8080"

networks:
  web:
    external: true
    name: traefik-proxy
