version: '3'

services:

  nginx:
    image: nginx:1.25.3
    container_name: nginx
    depends_on:
      - mlflow-server
      # - portfolio
    volumes:
      - ./server/html:/usr/share/nginx/html
      - ./server/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  mlflow-server:
    image: mlflow-server
    container_name: mlflow-server
    ports:
      - 5000:5000
  # portfolio:
  #   image: portfolio
  #   container_name: portfolio
  #   ports:
  #     - 1234:1234
