api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https        # tüm HTTP -> HTTPS (NPM "Force SSL" karşılığı)
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false     # sadece traefik.enable=true olanları al
    network: traefik-proxy
  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  le:
    acme:
      email: melikbugraozcelik@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
