version: '3.8'

services:
  greenhouse:
    build: .
    image: greenhouse:latest
    container_name: greenhouse
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.greenhouse.rule=Host(`greenhouse.melikbugraozcelik.com`)"
      - "traefik.http.routers.greenhouse.entrypoints=websecure"
      - "traefik.http.routers.greenhouse.tls.certresolver=le"
      - "traefik.http.routers.greenhouse.middlewares=hsts@file"
      - "traefik.http.services.greenhouse.loadbalancer.server.port=80"

networks:
  web:
    external: true
    name: traefik-proxy
