services:
  mlflow-server:
    image: mlflow-server
    build: .
    container_name: mlflow-server
    volumes:
      - ./mlruns:/usr/src/app/mlruns
      # - ./mlflow.db:/usr/src/app/mlflow.db
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mlflow.rule=Host(`mlflow.melikbugraozcelik.com`)"
      - "traefik.http.routers.mlflow.entrypoints=websecure"
      - "traefik.http.routers.mlflow.tls.certresolver=le"
      - "traefik.http.routers.mlflow.middlewares=office-ip@file,hsts@file"
      - "traefik.http.services.mlflow.loadbalancer.server.port=5000"

  optuna-db:
    image: postgres:16
    environment:
      POSTGRES_DB: optuna
      POSTGRES_USER: optuna
      POSTGRES_PASSWORD: optuna
    volumes:
      - ./data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U optuna -d optuna" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - web

  optuna-pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    # ports:
    #   - "5050:80"
    depends_on:
      - optuna-db
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.optuna.rule=Host(`optuna-pgadmin.melikbugraozcelik.com`)"
      - "traefik.http.routers.optuna.entrypoints=websecure"
      - "traefik.http.routers.optuna.tls.certresolver=le"
      - "traefik.http.routers.optuna.middlewares=office-ip@file,hsts@file"
      - "traefik.http.services.optuna.loadbalancer.server.port=80"

networks:
  web:
    external: true
    name: traefik-proxy
